### ISSUE TITLE
Request: Add ability to allow ships to go faster than standard speed

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/EssentialsPlugin#62]
I've tried doing this several ways, one by a mod downloaded from steam to modify the environment.sbc. And also my manually editing the C:\ProgramData\SpaceEngineersDedicated\Content\Data\Environment.sbc file directly. It works on plain SEDedicated but not under SESE. Not sure if it can just be allowed to edit it or if it is something you could just add as another option of Essentials.

**Comment by McyD** [comment]
I run SESE and speed mods work fine, you just have to make sure it is that last mod loaded, as any other mod that edits the environment, like a sky box, will break it due to a limitation in how it is implemented.  Best bet is to get a combo sky box/speed mod otherwise you are stuck with one or the other.

**Comment by LordNex** [comment]
Ive tried one that one of our admins made and it works fine on his vanilla server but not on mine. I don't have any custom skybox and I'm pretty sure it is the last in the list, but I'll double check that. Which one are you using? I see several on the workshop.

Thanks

**Comment by McyD** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=371740689

**Comment by LordNex** [comment]
Yea that worked, thanks
